# Copy this file to .streamlit/secrets.toml and fill in your actual values
# DO NOT commit the actual secrets.toml file to GitHub

[sheets]
# Google Sheets configuration
sheet_id = "1Rmj5fbhwkQivv98hR5GqCNhBkV8-EwEtEA74bsC6wAU"
schedule_tab = "ESPN Schedule Pull"
predictions_tab = "Predictions"

[apis]
# API Keys (replace with your actual keys)
cfbd_api_key = "YOUR_CFBD_API_KEY_HERE"
odds_api_key = "YOUR_ODDS_API_KEY_HERE"

[google_service_account]
# Google service account JSON contents (paste the entire JSON here as a string)
# Get this from your kentraining.json file
type = "service_account"
project_id = "your_project_id"
private_key_id = "your_private_key_id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n"
client_email = "your_service_account_email@your_project.iam.gserviceaccount.com"
client_id = "your_client_id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "your_cert_url"